DELETE FROM lang;

INSERT INTO lang VALUES (1,"Français",0,"fr-FR",14);
INSERT INTO lang VALUES (2,"English(US)",0,"en-US",14);
INSERT INTO lang VALUES (3,"English(UK)",0,"en-GB",14);
INSERT INTO lang VALUES (4,"Deutsch",0,"de-DE",14);
INSERT INTO lang VALUES (5,"Español",0,"es-ES",14);
INSERT INTO lang VALUES (6,"Italiano",0,"it-IT",10);
INSERT INTO lang VALUES (7,"Ελλάδα",1,"gr-GR",2);
INSERT INTO lang VALUES (8,"اللغةالعربية",1,"ar",2);
INSERT INTO lang VALUES (9,"Flemish",1,"nl-BE",2);
INSERT INTO lang VALUES (10,"Português",1,"pt-PT",2);
INSERT INTO lang VALUES (11,"čeština",1,"cs-CZ",2);
INSERT INTO lang VALUES (12,"Dansk",1,"da-DK",2);
INSERT INTO lang VALUES (13,"Nederlands",1,"nl-NL",2);
INSERT INTO lang VALUES (14,"Suomi",1,"fi-FI",2);
INSERT INTO lang VALUES (15,"Islenska",1,"is-IS",2);
INSERT INTO lang VALUES (16,"Østnorsk",1,"no-NO",2);
INSERT INTO lang VALUES (17,"Svenska",1,"sv-SE",2);
INSERT INTO lang VALUES (18,"Türkçe",1,"tr-TR",2);
INSERT INTO lang VALUES (19,"Словари",1,"ru-RU",2);
INSERT INTO lang VALUES (20,"językpolski",1,"pl-PL",2);
INSERT INTO lang VALUES (21,"PortuguêsdoBrasil",0,"pt-BR",10);
INSERT INTO lang VALUES (22,"Catalan",1,"ca-ES",2);
INSERT INTO lang VALUES (23,"日本(Japan)",1,"ja-JP",2);
INSERT INTO lang VALUES (24,"Français(CA)",1,"fr-CA",2);
INSERT INTO lang VALUES (25,"ประเทศไทย(Thai)",1,"th-TH",2);
INSERT INTO lang VALUES (26,"粤语(Cantonais)",1,"zh-yue",2);
INSERT INTO lang VALUES (27,"官话(Mandarin)",1,"zh-cnm-CN",2);
INSERT INTO lang VALUES (28,"English(AU)",1,"en-AU",2);
INSERT INTO lang VALUES (29,"English(IE)",1,"en-IE",2);
INSERT INTO lang VALUES (30,"English(IN)",1,"en-IN",2);
INSERT INTO lang VALUES (31,"English(ZA)",1,"en-ZA",2);
INSERT INTO lang VALUES (32,"Español(MX)",1,"es-MX",2);
INSERT INTO lang VALUES (33,"Basque",1,"eu-ES",2);
INSERT INTO lang VALUES (34,"한국말(Korea)",1,"ko-KR",2);
INSERT INTO lang VALUES (35,"हिन्दी(Hindi)",1,"hi-IN",2);
INSERT INTO lang VALUES (36,"Français (BE),",1,"fr-BE",2);
INSERT INTO lang VALUES (37,"Français",-1,"fr",1);
INSERT INTO lang VALUES (38,"English",-1,"en",1);
INSERT INTO lang VALUES (39,"Deutsch",-1,"de",1);
INSERT INTO lang VALUES (40,"Español",-1,"es",1);
INSERT INTO lang VALUES (41,"Italiano",-1,"it",1);
INSERT INTO lang VALUES (42,"Português",-1,"pt",1);

